FROM public.ecr.aws/lambda/nodejs:20-arm64 as build
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /build
COPY prisma ./prisma
COPY prisma/migrator.ts ./migrator.ts
COPY assets/migrator.package.json ./package.json
# Run npm install to generate package-lock.json needed by `npm ci`
RUN npm install
RUN npm ci

# https://esbuild.github.io/api/
# also refer to: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts
RUN npx esbuild migrator.ts --bundle --outdir=dist --platform=node --external:aws-sdk

FROM build as production
ARG NODE_ENV=production 
ENV NODE_ENV=${NODE_ENV} 
WORKDIR ${LAMBDA_TASK_ROOT}

COPY assets/migrator.package.json ./package.json
COPY prisma ./prisma
COPY --from=build /build/package-lock.json .

RUN npm ci --omit=dev
COPY --from=build /build/dist .
COPY --from=build /build/node_modules ./node_modules

CMD ["migrator.handler"]
